### ISSUE TITLE
Crear prototipos

### ISSUE THREAD

**Issue by djrock1987** [djrock1987/naves#4]
Crear Prototipos de las 3 naves

**Comment by Juancho47** [comment]
Se hace entrega de prototipo menor de 1 pulgada, mediano y grande, con la condicion que uno se pueda encajar dentro de otro.
![20170913_201206](https://user-images.githubusercontent.com/5251986/30409128-b9c32da6-98c8-11e7-8e55-c16a7d1d0453.jpg)
![20170913_201632](https://user-images.githubusercontent.com/5251986/30409130-b9c3810c-98c8-11e7-8898-16b0226313dd.jpg)
![20170913_201830](https://user-images.githubusercontent.com/5251986/30409129-b9c363d4-98c8-11e7-8acb-60988c88b12d.jpg)
